name: Deploy React app to Azure App Service (via serve)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Ensure serve is installed
        run: npm install serve

      - name: Create server.js
        run: |
          echo "const express = require('express');" > server.js
          echo "const path = require('path');" >> server.js
          echo "const app = express();" >> server.js
          echo "const PORT = process.env.PORT || 3000;" >> server.js
          echo "app.use(express.static(path.join(__dirname, 'dist')));" >> server.js
          echo "app.get('*', (req, res) => {" >> server.js
          echo "  res.sendFile(path.join(__dirname, 'dist', 'index.html'));" >> server.js
          echo "});" >> server.js
          echo "app.listen(PORT, () => console.log('Server running on port', PORT));" >> server.js

      - name: Upload to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IT-framework-prod'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
