name: Deploy React app to Azure App Service with Express

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install Express for server
        run: npm install express

      - name: Upload to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IT-framework-prod'  # ⚠️ Remplace par le nom exact de ton App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
